version: "3"
services:
    padmin-db:
        container_name: padmin-db
        build:
            context: "./padmin-api/db"
            dockerfile: "Dockerfile"
        ports:
            - "${DB_PORT}:${DB_PORT}"
        expose:
            - "${DB_PORT}"
        command: --default-authentication-plugin=mysql_native_password           
        environment:
            MYSQL_USER: "${DB_USER}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: padmin
        volumes:
            - ./padmin-api/db/data:/var/lib/mysql
        restart: always
        networks: 
            - padmin

    padmin-api:
        container_name: padmin-api
        build:
            context: "./padmin-api"
            dockerfile: "Dockerfile"
        restart: always
        volumes:
            - ./padmin-api:/home/node/app
        ports:
            - "${API_PORT}:${API_PORT}"
        depends_on: 
            - padmin-db
        environment:
            - WAIT_HOSTS=padmin-db:${DB_PORT}
            - WAIT_HOSTS_TIMEOUT=300
            - WAIT_SLEEP_INTERVAL=30
            - WAIT_HOST_CONNECT_TIMEOUT=30
            - API_PORT=${API_PORT}
            - DB_PORT=${DB_PORT}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
        command: sh -c "/wait && npm install && npm run dev:run"
        networks: 
            - padmin

    padmin-app:
        container_name: padmin-app
        build:
            context: "./padmin-app"
            dockerfile: "Dockerfile"
        restart: always
        volumes: 
            - ./padmin-app:/home/node/app
        ports: 
            - "${APP_PORT}:${APP_PORT}"
        depends_on: 
            - padmin-db
            - padmin-api
        command: sh -c "npm install && npm run build && npm start"
        # environment:
        #     - WAIT_HOSTS=padmin-api:9001
        #     - WAIT_HOSTS_TIMEOUT=300
        #     - WAIT_SLEEP_INTERVAL=30
        #     - WAIT_HOST_CONNECT_TIMEOUT=30
        networks: 
            - padmin

    padmin-proxy:
        container_name: padmin-proxy
        build:
            context: "./padmin-proxy"
            dockerfile: "Dockerfile"
        restart: always
        volumes: 
            - ./padmin-proxy/conf:/etc/nginx
            #- ./padmin-proxy/html:/usr/share/nginx/html
        ports: 
            - "${NGINX_PORT}:80"
        # command: nginx -s reload
        depends_on: 
            - padmin-db
            - padmin-api
        networks: 
            - padmin

networks:
  padmin:
    driver: bridge