FROM nginx:1.19.2-alpine

RUN apk add --no-cache bash curl

#config
#copy ./nginx.conf etc/nginx/nginx.conf

#content
#copy ./*.html /usr/share/nginx/html
#copy ./*.css /usr/share/nginx/html
#copy ./*.png /usr/share/nginx/html
#copy ./*.js /usr/share/nginx/html